config/routes.rb
LifeCycle::Application.routes.draw do

  devise_for :users

  root to: "fellowstatuses#index"

  resources :fellowstatuses
  resources :fellows
  resources :statuses

end

app/models/fellow.rb
class Fellow < ActiveRecord::Base
  attr_accessible :created_at, :email, :facebook, :linkedin,
                  :name, :notes, :twitter, :updated_at

  validates :name, presence: true

  has_many :fellowstatuses, dependent: :destroy
  has_many :statuses, through: :fellowstatuses

end

app/models/fellowstatus.rb
class Fellowstatus < ActiveRecord::Base
  attr_accessible :fellow_id, :status_id

  belongs_to :fellow
  belongs_to :status

  #after_create :close_old

  #scope :for, lambda do |fellow|

  #def close_old
    #(Fellowstatus.for(fellow).where(closed_at: nil) - [self]).each |fellowstatus| do
    #  fellowstatus.update_attribute(:closed_at, Time.current)
   # end
  #end
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :description, :name, :fellowstatus_id

  validates :name, presence: true

  has_many :fellowstatuses, dependent: :destroy
  has_many :fellows, through: :fellowstatuses

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fellows_controller.rb
class FellowsController < ApplicationController
  before_filter :find_fellow, :only => [:show,
                                       :edit,
                                       :update,
                                       :destroy]
  def index
    @fellows = Fellow.all
  end

  def new
    @fellow = Fellow.new
  end

  def create
    @fellow = Fellow.new(params[:fellow])
    if @fellow.save
      flash[:notice] = "Fellow has been added."
      redirect_to @fellow
    else
      flash[:alert] = "Fellow has not been added."
      render action: "new"
    end
  end

  def show
    @fellow = Fellow.find(params[:id])
  end

  def edit
    @fellow = Fellow.find(params[:id])
  end

  def update
    @fellow = Fellow.find(params[:id])
    if @fellow.update_attributes(params[:fellow])
      flash[:notice] = "Fellow has been updated."
      redirect_to @fellow
    else
      flash[:alert] = "Fellow has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @fellow = Fellow.find(params[:id])
    @fellow.destroy
    flash[:notice] = "Fellow has been deleted."
    redirect_to fellows_path
  end

private
  def find_fellow
    @fellow = Fellow.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The fellow you were looking for could not be found."
    redirect_to fellows_path
  end
end

app/controllers/fellowstatuses_controller.rb
class FellowstatusesController < ApplicationController
  before_filter :find_fellows_and_statuses, only: [:show, :edit, :update, :destroy]

  def index
    @fellowstatuses = Fellowstatus.all

  end

def new
    #@fellow = Fellow.new(params[:fellow])
    #@fellowstatus = @fellow.fellowstatus.build
    @fellowstatus = Fellowstatus.new
  end

  def create

    @fellow = Fellow.find(params[:fellowstatus][:fellow_id])
    @status = Status.find(params[:fellowstatus][:status_id])
    @fellowstatus = Fellowstatus.new(fellow_id: @fellow.id, status_id: @status.id)

    #@fellow = Fellow.new(params[:fellow])
    #@fellowstatus = @fellow.fellowstatus.build
    #@fellowstatus = Fellowstatus.build(params[:fellowstatus])
    #@fellowstatus.closed_old

    if @fellowstatus.save
      flash[:notice] = "Fellow Status has been added."

      redirect_to @fellowstatus
    else
     flash[:alert] = "Fellow Status has not been created."
     render action: "new"
    end
  end

  def show
    @fellowstatus = Fellowstatus.find(params[:id])
  end

  def edit
    @fellowstatus = Fellowstatus.find(params[:id])
  end

  def update
    #@fellow = Fellow.new(params[:fellow])
    #@fellowstatus = @fellow.fellowstatus.build
    #@fellowstatus = Fellowstatus.find(params[:id])
    @fellowstatus = Fellowstatus.find(params[:id])
    @fellowstatus.update_attributes(params[:fellowstatus])
        #@fellowstatus.time = Time.now
      #if @fellowstatus.update

      flash[:notice] = "Fellow Status has been updated"
        flash[:notice] = Time.now
        redirect_to @fellowstatus
      #else
       #flash[:alert] = "Fellow Status has not been updated."
        #render action: "edit"
      #end
  end

  def destroy
    @fellowstatus = Fellowstatus.find(params[:id])
    @fellowstatus.destroy
    flash[:notice] = "Fellow Status has been deleted."
    redirect_to fellowstatuses_path
  end

  private
  def find_fellows_and_statuses
    @fellow = Fellow.all
    @status = Status.all
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :find_status, :only => [:show, :edit, :update, :destroy]
  def index
    @statuses = Status.all
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(params[:status])
    if @status.save
      flash[:notice] = "Status has been created."
      redirect_to @status
    else
      flash[:alert] = "Status has not been created."
      render action: "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @status.update_attributes(params[:status])
    flash[:notice] = "Status has been updated."
    redirect_to @status
  end

  def destroy
    @status.destroy
    flash[:notice] = "Status has been deleted."
    redirect_to statuses_path
  end

  private
  def find_status
    @status = Status.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The status you were looking" +
                    " for could not be found."
    redirect_to statuses_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "life_cycle").join(" - ")
      end
    end
  end
end

app/helpers/fellows_helper.rb
module FellowsHelper
end

app/helpers/fellowstatuses_helper.rb
module FellowstatusesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/fellows/_form.html.erb
<%= form_for(@fellow) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </p>

  <p>
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </p>

  <p>
    <%= f.label :linkedin, "LinkedIn" %><br />
    <%= f.text_field :linkedin %>
  </p>

  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>


  <%= f.submit %>
<% end %>

app/views/fellows/edit.html.erb
<h2>Edit fellow</h2>
<%= render "form" %>

app/views/fellows/index.html.erb
<h2>Fellows</h2>
<table class="table table-bordered">
  <tr>
    <th>Name</th>
  </tr>
  <% @fellows.each do |fellow| %>
    <tr>
      <td><%= link_to fellow.name, fellow %></td>
    </tr>
<% end %>
</table>

app/views/fellows/new.html.erb
<h2>New Fellow</h2>
<%= render "form" %>

app/views/fellows/show.html.erb
<% title(@fellow.name, "Fellows") %>
<h2><%= @fellow.name %></h2>

<table class="table table-bordered">
  <tr>
    <th>Email</th>
    <th>Twitter Handle</th>
    <th>Facebook</th>
    <th>LinkedIn</th>
    <th>Notes</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <tr>
    <td><%= @fellow.email %></td>
    <td><%= @fellow.twitter %></td>
    <td><%= @fellow.facebook %></td>
    <td><%= @fellow.linkedin %></td>
    <td><%= @fellow.notes %></td>
    <td><%= link_to "Edit Fellow", edit_fellow_path(@fellow) %></td>
    <td><%= link_to "Delete Fellow",
     fellow_path(@fellow),
     :method => :delete,
     :confirm => "Wait. Are you SURE you want to delete this fellow?" %></td>
  </tr>

</table>
  <br />
  <br />

  <h2>Fellow History</h2>
  <table class="table table-bordered">
    <tr>
      <th>Date</th>
      <th>Status</th>
    </tr>
    <% @fellow.fellowstatuses.each do |fellow_status| %>
      <tr>
        <td><%= fellow_status.created_at.to_date %></td>
        <td><%= fellow_status.status.name %></td>
      </tr>
    <% end %>

  </table>

app/views/fellowstatuses/_form.html.erb
<%= form_for(@fellowstatus) do |f| %>
  <%= f.error_messages %>

<% if params[:fellow_id].present? %>

    <%= @fellowstatus.fellow.name %>

    <div class="field">
    <%= f.label :status %>
    <%= f.collection_select :status_id, Status.find(:all),
                            :id, :name, prompt: "Set a Status!" %> <br>
  </div>

 <% else %>

  <div class="field">
    <%= f.label :fellow_id %>
    <%= f.collection_select :fellow_id, Fellow.find(:all),
                            :id, :name, prompt: "Choose a Fellow!" %> <br>
  </div>

  <div class="field">
    <%= f.label :status_id %>
    <%= f.collection_select :status_id, Status.find(:all),
                            :id, :name, prompt: "Set a Status!" %> <br>
  </div>

<% end %>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/fellowstatuses/edit.html.erb
<%= form_for(@fellowstatus, url: { action: "create", method: :put }) do |f| %>
  <%= f.error_messages %>


<%= @fellowstatus.fellow.name %>

<h2>Update Status</h2>
 <div class="field">
    <%= f.label :status %>
    <%= f.collection_select :status_id, Status.find(:all),
                            :id, :name, prompt: "Set a Status!" %> <br>
  </div>


<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/fellowstatuses/index.html.erb
<h2>Recent Fellow Statuses!</h2>
<table class="table table-bordered" bgcolor="#FFF" style="opacity:.95">
  <tr>
    <th>Fellow</th>
    <th>Status</th>
    <th>Last Updated At</th>
    <th>History</th>
  </tr>

  <% @fellowstatuses.each do |fellowstatus| %>
    <tr>
      <td><%= fellowstatus.fellow.name %></td>
      <td><%= fellowstatus.status.name %></td>
      <td><%= fellowstatus.updated_at.strftime('%B %d, %Y') %></td>
      <td><%= link_to "History", :fellows %></td>
    </tr>
  <% end %>

</table>

<br />
<br />

<%= link_to "Look At All Statuses", :statuses %>
<%= link_to "Look At All Fellows", :fellows %>

app/views/fellowstatuses/new.html.erb
<h2>Set a Fellow Status</h2>
<%= render "form" %>
<%= link_to 'Back', fellowstatuses_path %>

app/views/fellowstatuses/show.html.erb
<% title(@fellowstatus.fellow.name, "Fellow Statuses") %>
<h1>Fellow Story</h1>
<h2>
  <b>Fellow:</b>
  <%= link_to @fellowstatus.fellow.name %>
</h2>

<h2>
  <b>Current Status:</b>
  <%= @fellowstatus.status.name %>
</h2>

  <h2>Created at: <%= Time.now.to_date %></h2>



<%= link_to "View all Fellow Statuses", fellowstatuses_path %>
<%= link_to "Edit Fellow Status", edit_fellowstatus_path(@fellowstatus) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  <% if content_for?(:title) %>
    <%= yield(:title) %>
  <% else %>
    life_cycle
  <% end %>
</title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"></script>


</head>
<body>

  <div class="navbar navbar-inverse">

<%= image_tag "CFlogo.png", id: "corner_logo" %>
<div id="buttons">
    <button type="button" class="btn btn-default navbar-btn pull-left"><%= link_to "Home", root_path %></button>
    <button type="button" class="btn btn-default navbar-btn pull-left"><%= link_to "Add New Fellow", new_fellow_path %></button>
    <button type="button" class="btn btn-default navbar-btn pull-left"><%= link_to "New Status", new_status_path %></button>
    <button type="button" class="btn btn-default navbar-btn pull-left"><%= link_to "New Fellow Status", new_fellowstatus_path %></button></div>

      <% if user_signed_in? %>
        <p class="navbar-text pull-right">Signed in as <a href="#" class="navbar-link"><%= current_user.email %></a></p>
      <% else %>
        <button type="button" class="btn btn-default navbar-btn pull-right"><%= link_to "Sign up", new_user_registration_path %></button>
        <button type="button" class="btn btn-default navbar-btn pull-right"><%= link_to "Sign in", new_user_session_path %></button>
      <% end %>

      <button type="button" class="btn btn-default navbar-btn pull-right"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></button>

  </div>

   <% flash.each do |key, value| %>
    <div class='flash' id='<%=key %>'>
      <%=value %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <%= f.error_messages %>
  <p>
    <%=f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/statuses/edit.html.erb
<h2>Edit Status</h2>
<%= render "form" %>

app/views/statuses/index.html.erb
<h2>List of Statuses</h2>
<table class="table table-bordered">
  <tr>
    <th>Status</th>
  </tr>
  <% @statuses.each do |status| %>
    <tr>
      <td><%= link_to status.name, status %></td>
    </tr>
  <% end %>
</table>

app/views/statuses/new.html.erb
<h2>New Status</h2>
<%= render "form" %>

app/views/statuses/show.html.erb
<% title(@status.name, "Statuses") %>
<h2><%= @status.name %></h2>

<%= link_to "Edit Status", edit_status_path(@status) %>
<%= link_to "Delete Status",
     status_path(@status),
     :method => :delete,
     :confirm => "Are you sure you want to delete this status?" %>
<%= link_to "Add new Status", new_status_path(@status) %>
<%= link_to "View all Stasuses", statuses_path %>